#!/usr/bin/env python3
"""Generate config/mission_<world>.yaml from mujoco_world.WORLDS.

The suggested goals live in the world registry: writing them by hand in the
mission files makes them diverge silently as soon as a geometry is touched (it
already happened with dead_end, lengthened from 8 to 12 m, and with horseshoe
from 5 to 12 m). Here they are all regenerated:

    python3 src/g1_sim/scripts/gen_missions.py
"""
import os
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _ROOT)
from g1_sim.mujoco_world import WORLDS  # noqa: E402

OUT = os.path.join(_ROOT, "config")

TEMPLATE = """# GENERATED BY scripts/gen_missions.py — do not edit by hand.
# World: {name} — {desc}
#
#   ros2 launch g1_sim g1_a_star_mpc.launch.py world:={name} \\
#        use_mission:=true \\
#        mission_file:=$(ros2 pkg prefix g1_sim)/share/g1_sim/config/{fname}
#
# reach_radius > goal_reached_radius (0.25) of the G1 profile: below that value
# a_star_node stops replanning, so a tighter threshold would stall the mission one
# step short of the finish.
frame_id: odom
reach_radius:     0.35
leg_timeout_sec: {timeout:.1f}

waypoints:
  - {{ x: {gx:6.2f}, y: {gy:6.2f}, yaw: 0.0, name: "goal" }}
"""


def main() -> int:
    for name, info in sorted(WORLDS.items()):
        gx, gy = info["goal"]
        sx, sy, _ = info["spawn"]
        diretta = ((gx - sx) ** 2 + (gy - sy) ** 2) ** 0.5
        # generous margin: a concave trap can cost 3x the direct distance, at
        # ~0.28 m/s on average. Better too much than seeing a leg fail on timeout
        # and believing it was the planner.
        # The long-wall worlds require following a wall for tens of metres (and in
        # the worst case doing it again backwards), so the time cannot be derived
        # from the direct distance: it is declared in the world registry.
        timeout = float(info.get("timeout",
                                 max(180.0, round(3.5 * diretta / 0.28, -1))))
        fname = f"mission_{name}.yaml"
        with open(os.path.join(OUT, fname), "w") as fh:
            fh.write(TEMPLATE.format(name=name, desc=info["desc"], fname=fname,
                                     gx=gx, gy=gy, timeout=timeout))
        print(f"  {fname:34s} goal=({gx:6.2f},{gy:6.2f})  timeout={timeout:.0f}s")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
